version: '3.8'
services:
    php-apache3:
      container_name: php-apache3
      build: 
          context: ./web
          dockerfile: dockerfile
      volumes: 
        - ./authentication.php:/var/www/html/authentication.php
        - ./connection.php:/var/www/html/connection.php
        - ./sqli3.php:/var/www/html/sqli3.php
      ports: 
        - 80:80
      depends_on: 
        - sql_db3
      networks: 
        - netConnect3
        - dbConnect3
    
    sql_db3 :
      container_name: sql_db3
      image: mysql
      environment:
          MYSQL_ROOT_PASSWORD: CokGizliParola
          MYSQL_DATABASE: letmehack_db
      volumes: 
        - ./sql-scripts/:/docker-entrypoint-initdb.d/
      restart: always
      networks: 
          - dbConnect3

networks:
    dbConnect3:
        internal: true
    netConnect3:
