version: '3.8'
services:
    php-apache:
      container_name: php-apache1
      build: 
          context: ./web
          dockerfile: dockerfile
      volumes: 
        - ./authentication.php:/var/www/html/authentication.php
        - ./connection.php:/var/www/html/connection.php
        - ./sqli1.php:/var/www/html/sqli1.php
      ports: 
        - 80:80
      depends_on: 
        - sql_db
      networks: 
        - netConnect
        - dbConnect
    
    sql_db :
      container_name: sql_db1
      image: mysql
      environment:
          MYSQL_ROOT_PASSWORD: CokGizliParola
          MYSQL_DATABASE: letmehack_db
      volumes: 
        - ./sql-scripts/:/docker-entrypoint-initdb.d/
      restart: always
      networks: 
          - dbConnect

networks:
    dbConnect:
        internal: true
    netConnect:
